### ISSUE TITLE
Error click refreshbutton

### ISSUE THREAD

**Issue by xuantuongdhqn** [HsuanXyz/ionic2-pincode-input#6]
**step 1**:  We didnt input 
**step 2**:  Click button "refresh"

**desire**: input will not show anything
**reality**: border of input wille be resized

**Comment by hsuanxyz** [comment]
your package.json

```diff
 "dependencies": {
      ...
-    "ionic2-pincode-input": "0.0.6",
+    "ionic2-pincode-input": "0.0.7",
  }
```
run 

```bash
npm i 
```

**Comment by xuantuongdhqn** [comment]
thanks for help
