### ISSUE TITLE
Backbutton of keyboard

### ISSUE THREAD

**Issue by xuantuongdhqn** [HsuanXyz/ionic2-pincode-input#7]
When you click back button,  round input will descrease by times click backbutton.

**Comment by hsuanxyz** [comment]
😂 Sorry i was not fully tested

**Comment by hsuanxyz** [comment]
```diff
 "dependencies": {
      ...
-    "ionic2-pincode-input": "0.0.7",
+    "ionic2-pincode-input": "0.0.8",
  }
```

**Comment by xuantuongdhqn** [comment]
Okie, thanks you very much

**Comment by xuantuongdhqn** [comment]
Hi Hsuan Lee,
Thanks for your help.
😀

2017-06-07 19:46 GMT+07:00 Hsuan Lee <notifications@github.com>:
