### ISSUE TITLE
key 0 not working

### ISSUE THREAD

**Issue by soufiene-slimi** [HsuanXyz/ionic2-pincode-input#9]
`openPinCode():any{

    let pinCode =  this.pincodeCtrl.create({
      title:'Pincode',
      passSize: 4,
      hideForgotPassword: true,
      enableBackdropDismiss: true
    });

    pinCode.present();

    pinCode.onDidDismiss( (code,status) => {

      if(status === 'done'){

        this.code = code;
        let toast = this.toastCtrl.create({
          message: code,
          duration: 3000,
          position: 'top'
        });
        toast.present();
      }

    })

  }`

i tape 1407 and the toast shows 147

**Comment by hsuanxyz** [comment]
`npm install ionic2-pincode-input@0.0.9 --save`

Thanks! @soufiene-slimi @Jordan4jc
